[package]
name = "release-test"
version = "0.2.0"
authors = ["Catherine Garabedian <catherine@kubos.co>"]
edition = "2018"

[dependencies]
failure = "0.1.2"
kubos-app = { git = "https://github.com/kubos/kubos" }
log = "^0.4.0"