[app-service.addr]
ip = "0.0.0.0"
port = 8000

[clyde-3g-eps-service]
bus = "/dev/i2c-1"

[clyde-3g-eps-service.addr]
ip = "0.0.0.0"
port = 8001

[mai400-service.addr]
ip = "0.0.0.0"
port = 8002

[novatel-oem6-service]
bus = "/dev/ttyS4"

[novatel-oem6-service.addr]
ip = "0.0.0.0"
port = 8003

[pumpkin-mcu-service]

[pumpkin-mcu-service.modules]
[pumpkin-mcu-service.modules.sim]
address = 80
[pumpkin-mcu-service.modules.gpsrm]
address = 81
[pumpkin-mcu-service.modules.pim]
address = 83
[pumpkin-mcu-service.modules.rhm]
address = 85

[pumpkin-mcu-service.addr]
ip = "0.0.0.0"
port = 8004

[telemetry-service]
database = "/home/system/kubos/telemetry.db"
direct_port = 8005

[telemetry-service.addr]
ip = "0.0.0.0"
port = 8006

[isis-ants-service.addr]
ip = "0.0.0.0"
port = 8007

[isis-ants-service]
bus = "/dev/i2c-0"
primary = "0x31"
secondary = "0x32"
antennas = 4
wd_timeout = 10

[file-transfer-service]
storage_dir = "/home/system/file-storage"

[file-transfer-service.addr]
ip = "0.0.0.0"
port = 8008

[monitor-service.addr]
ip = "0.0.0.0"
port = 8009

[shell-service.addr]
ip = "0.0.0.0"
port = 8010

[nsl-duplex-comms-service]
bus = "/dev/ttyS2"

[nsl-duplex-comms-service.comms]
max_num_handlers = 10
downlink_ports = [15001]
timeout = 15000
satellite_ip = "127.0.0.2"

[nsl-duplex-comms-service.addr]
ip = "127.0.0.2"
port = 8011